# https://github.com/ram133/picoclaw/bill.py
# Path: picoclaw/bill.py

import os
from wp import post

# RATE CONFIGURATION
RATE_PER_MINUTE = 1.00

def generate_quote(project_name, estimated_minutes):
    """Autonomously calculates and formats a professional quote."""
    total = estimated_minutes * RATE_PER_MINUTE
    quote_body = f"""
    <h2>Service Quote: {project_name}</h2>
    <p><strong>Estimated Time:</strong> {estimated_minutes} minutes</p>
    <p><strong>Rate:</strong> ${RATE_PER_MINUTE}/min</p>
    <p><strong>Total Estimate:</strong> ${total:,.2f}</p>
    <hr>
    <p>This quote was autonomously generated by the RayNV Engine. 
    To proceed, please confirm via the B2B portal.</p>
    """
    
    # Push quote to WordPress for record keeping/client review
    post(f"Quote: {project_name}", quote_body)
    print(f"Action: Quote Generation. Result: ${total} estimate sent to WP.")

if __name__ == "__main__":
    # Test generation for a standard automation audit
    generate_quote("Standard System Audit", 120)
